const WA="https://wa.me/919330877141?text=Namaste%20Pt.%20Nikunj%20Kr%20Sahal%2C%20I%20would%20like%20to%20book%20a%20consultation.";
const PHONE="+91 9330877141";
const services=[
 {n:"01",icon:"☀",title:"Vedic Astrology",desc:"Birth-chart based guidance for relationships, career, important decisions and life planning."},
 {n:"02",icon:"✦",title:"Numerology",desc:"Explore the traditional meaning of numbers connected with your date of birth and name."},
 {n:"03",icon:"⌂",title:"Vastu Shastra",desc:"Traditional Vastu guidance for homes, offices, shops and other spaces."},
 {n:"04",icon:"☾",title:"Palmistry",desc:"Traditional palm reading focused on patterns, tendencies and personal reflection."}
];
const signs=["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const glyphs=["♈","♉","♊","♋","♌","♍","♎","♏","♐","♑","♒","♓"];
function Button({href=WA,children,secondary=false}){return <a className={`btn ${secondary?"btn-secondary":"btn-primary"}`} href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined}>{children}</a>}
function SectionLabel({children}){return <p className="kicker">{children}</p>}
export default function Home(){return <main id="top">
 <nav className="nav"><a className="brand" href="#top"><span className="brand-mark">ॐ</span><span><b>JYOTISH SHIVALAYA</b><small>VEDIC WISDOM • PERSONAL GUIDANCE</small></span></a><div className="nav-links"><a href="#about">About</a><a href="#services">Services</a><a href="#horoscope">Horoscope</a><a href="#contact">Contact</a></div><Button>Book Consultation</Button></nav>
 <header className="hero"><div className="stars" aria-hidden="true">{Array.from({length:10}).map((_,i)=><i key={i}/>)}</div><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="hero-content"><div className="pill">✦ ASTROLOGY • VASTU • NUMEROLOGY • PALMISTRY</div><SectionLabel>ANCIENT WISDOM FOR MODERN LIFE</SectionLabel><h1>Find clarity.<br/><em>Follow your stars.</em></h1><p className="lead">Personalized guidance rooted in traditional Vedic practices, with a clear and practical approach for modern life.</p><div className="actions"><Button>Book a Consultation <span>↗</span></Button><Button href="#services" secondary>Explore Services</Button></div><div className="trust"><span><b>10+</b> Years of experience</span><span><b>2000+</b> Clients guided</span><span><b>₹299</b> Online consultation</span></div></div><div className="hero-card"><div className="card-symbol">✦</div><div><small>ASTROLOGER</small><strong>Pt. Nikunj Kr Sahal</strong><span>Astrology • Vastu • Numerology • Palmistry</span></div></div></header>
 <section className="intro section" id="about"><div><SectionLabel>ABOUT JYOTISH SHIVALAYA</SectionLabel><h2>Traditional wisdom,<br/><em>personal guidance.</em></h2></div><div className="intro-copy"><p>Jyotish Shivalaya provides online consultations in Astrology, Vastu, Numerology and Palmistry. Each session is designed around the information you share and aims to provide thoughtful traditional guidance for your questions.</p><p className="muted">Astrology and related services are intended for general guidance and personal reflection. Interpretations may vary according to individual circumstances and birth charts.</p><div className="mini-points"><span>✓ Online consultations</span><span>✓ Direct WhatsApp support</span><span>✓ Traditional methods</span></div></div></section>
 <section className="section services" id="services"><div className="section-heading"><div><SectionLabel>WHAT WE OFFER</SectionLabel><h2>Areas of <em>guidance</em></h2></div><p>Choose the traditional practice that matches the kind of guidance you are looking for.</p></div><div className="service-grid">{services.map(s=><article className="service" key={s.title}><div className="service-top"><span className="service-number">{s.n}</span><span className="service-icon">{s.icon}</span></div><h3>{s.title}</h3><p>{s.desc}</p><a href={WA} target="_blank" rel="noreferrer">Discuss on WhatsApp <span>→</span></a></article>)}</div></section>
 <section className="consultation"><div className="consultation-glow"/><div className="consultation-copy"><SectionLabel>ONLINE CONSULTATION</SectionLabel><h2>Personal guidance,<br/><em>from anywhere.</em></h2><p>Book a direct online consultation through WhatsApp. Tell us your area of interest and receive the next steps.</p><div className="price-row"><strong>₹299</strong><span>Online consultation<br/>Simple • Direct • Convenient</span></div><Button>WhatsApp {PHONE} ↗</Button></div><div className="mandala" aria-hidden="true"><div>ॐ</div><span>✦</span><span>✦</span><span>✦</span><span>✦</span></div></section>
 <section className="section horoscope" id="horoscope"><div className="section-heading"><div><SectionLabel>DAILY GUIDANCE</SectionLabel><h2>12 signs. <em>One sky.</em></h2></div><p>Explore the zodiac signs and connect with us for general sign-based astrology content.</p></div><div className="zodiac-grid">{signs.map((s,i)=><a href={WA} target="_blank" rel="noreferrer" key={s}><span>{glyphs[i]}</span><div><b>{s}</b><small>Daily guidance</small></div><strong>→</strong></a>)}</div></section>
 <section className="feature-strip"><div><SectionLabel>WHY JYOTISH SHIVALAYA</SectionLabel><h2>A calm space for<br/><em>meaningful questions.</em></h2></div><div className="feature-list"><div><b>01</b><span><strong>Personal attention</strong><small>Consultation centered on your questions.</small></span></div><div><b>02</b><span><strong>Traditional approach</strong><small>Guidance inspired by established practices.</small></span></div><div><b>03</b><span><strong>Easy online access</strong><small>Connect from wherever you are.</small></span></div></div></section>
 <section className="astro-fortune" id="astro-fortune"><div><SectionLabel>OUR SISTER BRAND</SectionLabel><h2>Astro <em>Fortune</em></h2><p>Follow our sister brand for regular astrology, zodiac, numerology and spiritual content.</p></div><Button href={WA} secondary>Ask about Astro Fortune ↗</Button></section>
 <section className="contact section" id="contact"><div className="contact-inner"><div><SectionLabel>LET’S CONNECT</SectionLabel><h2>Ready to begin<br/><em>your consultation?</em></h2><p>Send a WhatsApp message to ask a question or book an online consultation.</p></div><div className="contact-action"><div className="wa-icon">◔</div><span>WHATSAPP</span><strong>{PHONE}</strong><Button>Start a Conversation ↗</Button></div></div></section>
 <footer><div className="footer-main"><a className="footer-brand" href="#top"><span className="brand-mark">ॐ</span><div><b>JYOTISH SHIVALAYA</b><small>Astrologer Pt. Nikunj Kr Sahal</small></div></a><div className="footer-links"><a href="#about">About</a><a href="#services">Services</a><a href="#horoscope">Horoscope</a><a href="#contact">Contact</a></div></div><div className="footer-bottom"><span>Astro Fortune — Sister Brand</span><a href={WA} target="_blank" rel="noreferrer">WhatsApp: {PHONE}</a><small>Disclaimer: Astrology, Vastu, Numerology and Palmistry services are provided for general guidance and informational purposes. Results and interpretations may vary according to individual circumstances and birth charts. These services are not a substitute for professional medical, legal or financial advice.</small><small>© 2026 Jyotish Shivalaya. All Rights Reserved.</small></div></footer>
 </main>}
